[project]
name = "m-pgibbs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "numba>=0.61.2",
    "numpy>=2.2.5",
    "scipy>=1.15.2",
    "tqdm>=4.67.1",
]
